gui:
  spinner:
    frames:
      - ":<"
      - ":c"
      - ":("
      - ":I"
      - ":)"
      - ":>"
      - ":D"
      - ":O"
    rate: 80
  nerdFontsVersion: "3"
  showFileIcons: false
git:
  paging:
    externalDiffCommand: difft --color=always
os:
  editPreset: "nvim"
